# Generated by Django 3.1.7 on 2021-10-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(max_length=45)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('endereco', models.TextField(max_length=100)),
                ('telefone', models.TextField(max_length=13)),
            ],
        ),
    ]
