# Generated by Django 3.1.7 on 2021-04-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('pedido', '0003_auto_20210406_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='produto',
            field=models.ManyToManyField(to='produto.Produto'),
        ),
    ]
