# Generated by Django 3.1.7 on 2021-04-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
