# Generated by Django 3.1.7 on 2021-04-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_pedido_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
