# Generated by Django 3.1.7 on 2021-04-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idProduto', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=90)),
                ('preco', models.DecimalField(decimal_places=2, default=0.01, max_digits=6)),
                ('quantidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
    ]
